version: 2
jobs:
  build-and-test:
    machine: true
    steps:
      - checkout
     
      # Build the flask hello app
      - run: docker build -f flask.Dockerfile -t hello-circle:1.0.0 .

      # Build the selenium test image
      - run: docker build -f seleniumtest.Dockerfile -t test-hello-circle:1.0.0 .

      # Run the flask hello app
      - run: docker run -d -p 5000:5000 hello-circle:1.0.0

      # Run the selenium test image
      - run: docker run --network="host" test-hello-circle:1.0.0

  deploy:
    machine: true
    steps:
      - checkout

      # Rebuild flask app to be pushed
      - run: docker build -f flask.Dockerfile -t tunzor/hello-circle:1.0.0 .

      # Push image to docker hub
      - run: docker push tunzor/hello-circle:1.0.0 