version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
     
      # Build the flask hello app
      - run: 
        name: Build flask web app
        command: docker build -f flask.Dockerfile -t hello-circle:1.0.0 .

      # Build the selenium test image
      - run: 
        name: Build selenium testing image
        command: docker build -f seleniumtest.Dockerfile -t test-hello-circle:1.0.0 .

      # Run the flask hello app
      - run: 
        name: Start the flask web app container
        command: docker run -d -p 5000:5000 hello-circle:1.0.0

      # Run the selenium test image
      - run: 
        name: Run the selenium container and test the flask web app
        command: docker run --network="host" test-hello-circle:1.0.0

  deploy:
    machine: true
    steps:
      - run: echo Deploying!
      # - checkout
      # # Rebuild flask app to be pushed
      # - run: docker build -f flask.Dockerfile -t tunzor/hello-circle:1.0.0 .

      # # Push image to docker hub
      # - run: docker push tunzor/hello-circle:1.0.0 

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build